
const $=s=>document.querySelector(s);
let level="3",module=0,time=1200,timer=null,inventory=[],rank="CADET",hints=0;
const names=["CHAIN LOCK","UNIFORM INSPECTION","INTEL SCRAMBLE","GRID VECTOR","COMMAND BYPASS"];
const hintsText=[
"One chain-of-command billet is missing. Put the visible billets in order first, then identify the missing billet.",
"Four uniform areas are interactive. Inspect ribbons, insignia alignment, belt/buckle area, and another visible uniform detail.",
"The decoder is not random: every solved leadership word contributes one digit. Watch the word lengths.",
"Use the answers to the three knowledge checks as movement instructions. The correct destination is not the starting cell.",
"The final code is built from assets already in your inventory. Read each recovered asset carefully."
];
function show(id){["briefing","ops","complete","failed"].forEach(x=>$("#"+x).classList.add("hidden"));$("#"+id).classList.remove("hidden")}
function hud(){let m=Math.floor(Math.max(time,0)/60),s=String(Math.max(time,0)%60).padStart(2,"0");$("#clock").textContent=`${m}:${s}`;$("#rank").textContent=rank;$("#status").textContent=module>=5?"RESTORED":module>0?"ACTIVE":"STANDBY";progress()}
function progress(){$("#progress").innerHTML=names.map((n,i)=>`<div class="fw ${i<module?"done":i===module?"current":""}">${i<module?"✓":"▸"} FIREWALL ${i+1} // ${n}</div>`).join("")}
function inv(){$("#inventory").innerHTML=inventory.length?inventory.map(x=>`<div class="asset">${x}</div>`).join(""):`<p class="muted">No assets recovered.</p>`}
function feedback(msg,bad=false){$("#feedback").innerHTML=`<div class="${bad?"bad":"good"}">${msg}</div>`}
function unlock(asset){inventory.push(asset);inv();module++;rank=module>=4?"C/MAJ":module>=2?"C/CPT":"C/SGT";hud();setTimeout(()=>module>=5?finish():render(),900)}
$("#startBtn").onclick=()=>{if(!$("#callsign").value.trim())return alert("Enter a callsign.");level=$("#path").value;show("ops");$("#status").textContent="ACTIVE";render();timer=setInterval(()=>{time--;hud();if(time<=0){clearInterval(timer);show("failed")}},1000)}
$("#hintBtn").onclick=()=>{if(module>=5)return;time=Math.max(0,time-60);hints++;$("#hintBox").textContent="INTEL: "+hintsText[module];hud()}
function render(){hud();$("#feedback").innerHTML="";$("#moduleTag").textContent=`FIREWALL ${module+1} OF 5 // LET ${level}`;$("#moduleTitle").textContent=names[module];$("#moduleState").textContent="ACTIVE";let briefs=[
"The rogue protocol corrupted the battalion hierarchy. Restore the visible chain, then identify the missing command billet.",
"Inspection data has been sabotaged. Locate four visible discrepancies to reconstruct the inspection decoder.",
"Firewall Three has fragmented the decoder into scrambled leadership concepts. Every solved word reveals part of the key.",
"The protocol has moved the bypass key onto a tactical grid. Solve the knowledge checks, then identify the destination.",
"All recovered assets must now be fused into one final command bypass."
];$("#moduleBrief").textContent=briefs[module];[chain,uniform,scramble,mapPuzzle,bypass][module]()}
function chain(){let items=level==="3"?["Battalion Commander","Battalion Command Sergeant Major","Company Commander","Platoon Leader","Squad Leader"]:["Battalion Commander","Battalion Command Sergeant Major","S-3 / Operations Officer","Company Commander","Platoon Leader","Squad Leader"];let correct=[...items];items.sort(()=>Math.random()-.5);let p=$("#puzzle");p.innerHTML=`<div class="terminal">SECURITY NOTE: One senior command billet was deleted from the database. Restore the remaining structure first.</div><div id="sort" class="sortlist"></div><button id="checkOrder">VERIFY STRUCTURE</button><div id="missing" class="terminal hidden">MISSING BILLET ABBREVIATION: <input id="missingInput" placeholder="ENTER ABBREVIATION"><button id="missingBtn">AUTHENTICATE</button></div>`;function draw(){let s=$("#sort");s.innerHTML="";items.forEach((x,i)=>{let d=document.createElement("div");d.className="sortitem";d.innerHTML=`<span>${i+1}. ${x}</span><div><button data-u="${i}">▲</button><button data-d="${i}">▼</button></div>`;s.appendChild(d)});s.querySelectorAll("[data-u]").forEach(b=>b.onclick=()=>{let i=+b.dataset.u;if(i){[items[i-1],items[i]]=[items[i],items[i-1]];draw()}});s.querySelectorAll("[data-d]").forEach(b=>b.onclick=()=>{let i=+b.dataset.d;if(i<items.length-1){[items[i+1],items[i]]=[items[i],items[i+1]];draw()}})}draw();$("#checkOrder").onclick=()=>{if(JSON.stringify(items)!==JSON.stringify(correct))return feedback("STRUCTURE REJECTED // Recheck the hierarchy.",true);$("#missing").classList.remove("hidden");feedback("VISIBLE STRUCTURE RESTORED // Identify the missing billet.")};$("#missingBtn").onclick=()=>{let a=$("#missingInput").value.trim().toUpperCase().replace(/\./g,"");if(["XO","BN XO","BATTALION XO"].includes(a))unlock("HIERARCHY KEY // 7");else feedback("ACCESS DENIED // Missing billet not authenticated.",true)}}
function uniform(){let p=$("#puzzle");p.innerHTML=`<div class="uniformWrap"><div><div class="cadet"><div class="head"></div><div class="torso"></div><div class="shirtline"></div><div class="belt"></div><div class="buckle"></div><div class="ribbons"><i></i><i></i><i></i><i></i><i></i><i></i></div><div class="disk left"></div><div class="disk right"></div><div class="violation v1" data-v="0" title="Inspect ribbon area"></div><div class="violation v2" data-v="1" title="Inspect insignia"></div><div class="violation v3" data-v="2" title="Inspect belt"></div><div class="violation v4" data-v="3" title="Inspect alignment"></div></div><p class="muted">Click the four suspected inspection discrepancies.</p></div><div><h3>INSPECTION PIXEL DECODER</h3><div id="pixels" class="pixelgrid">${Array.from({length:16},(_,i)=>`<div class="pixel" id="px${i}"></div>`).join("")}</div><div class="terminal">4 confirmed discrepancies will illuminate a decoder symbol.</div></div></div>`;let found=new Set(),pattern=[1,4,6,9,11,14];document.querySelectorAll(".violation").forEach(v=>v.onclick=()=>{found.add(v.dataset.v);v.classList.add("found");pattern.slice(0,Math.ceil(found.size*1.5)).forEach(i=>$("#px"+i).classList.add("on"));if(found.size===4){feedback("INSPECTION COMPLETE // Pixel decoder forms the numeral 4.");setTimeout(()=>unlock("INSPECTION PIXEL // 4"),1000)}})}
function scramble(){let words=level==="3"?[["TIGRINTEY","INTEGRITY"],["DEEVICEN","EVIDENCE"],["IRPOITRY","PRIORITY"]]:[["ROCORBORATION","CORROBORATION"],["TARELIATION","RETALIATION"],["GEDELATION","DELEGATION"]];let i=0,p=$("#puzzle");function q(){if(i>=words.length){let digit=level==="3"?"8":"2";feedback("DECODER RECONSTRUCTED // Word-length checksum accepted.");setTimeout(()=>unlock("WORD DECODER // "+digit),900);return}p.innerHTML=`<div class="terminal">FRAGMENT ${i+1}/3<br><br><span style="font-size:30px;color:#ffb21c;letter-spacing:6px">${words[i][0]}</span><input id="scr" placeholder="UNSCRAMBLE"><button id="scrBtn">DECRYPT</button></div>`;$("#scrBtn").onclick=()=>{let n=s=>s.toUpperCase().replace(/[^A-Z]/g,"");if(n($("#scr").value)===n(words[i][1])){i++;q()}else feedback("DECRYPTION FAILED // Try again.",true)}}q()}
function mapPuzzle(){let p=$("#puzzle");let qs=level==="3"?[["How many Army Values are represented by LDRSHIP?","7"],["How many letters are in CPR?","3"],["How many points define a cardinal compass?","4"]]:[["How many Army Values are represented by LDRSHIP?","7"],["How many degrees are in a full circle?","360"],["How many digits are normally used in a four-digit grid coordinate?","4"]];let answers=[],qi=0;function ask(){if(qi<3){p.innerHTML=`<div class="clue">ORDER ${qi+1}/3 // ${qs[qi][0]}</div><input id="qa" placeholder="ENTER NUMERIC ANSWER"><button id="qab">TRANSMIT</button>`;$("#qab").onclick=()=>{if($("#qa").value.trim()===qs[qi][1]){answers.push(qs[qi][1]);qi++;ask()}else feedback("INCORRECT ORDER RESPONSE.",true)};return}let target=level==="3"?22:28;p.innerHTML=`<div class="terminal">ORDERS VERIFIED: ${answers.join(" // ")}<br>START CELL = A1. Apply the recovered movement logic and select the final grid destination.</div><div id="map" class="map"></div>`;let m=$("#map");for(let i=0;i<36;i++){let c=document.createElement("div");c.className="cell"+(i===0?" start":"");c.textContent=String.fromCharCode(65+Math.floor(i/6))+(i%6+1);c.onclick=()=>{if(i===target){c.classList.add("target");feedback("GRID VECTOR CONFIRMED // Coordinate cache recovered.");setTimeout(()=>unlock("GRID CACHE // "+(level==="3"?"81":"63")),900)}else feedback("VECTOR MISS // Recalculate destination.",true)};m.appendChild(c)}}ask()}
function bypass(){let p=$("#puzzle");let code=level==="3"?"7481":"74263";p.innerHTML=`<div class="terminal">FINAL FIREWALL<br><br>BUILD THE BYPASS FROM YOUR DIGITAL INVENTORY IN RECOVERY ORDER.<br>LET ${level} SECURITY PROTOCOL REQUIRES ${code.length} DIGITS.</div><div class="codeSlots">${Array.from({length:code.length},()=>"<span>•</span>").join("")}</div><input id="finalCode" maxlength="${code.length}" placeholder="ENTER FINAL BYPASS"><button id="finalBtn">EXECUTE COMMAND BYPASS</button>`;$("#finalBtn").onclick=()=>{if($("#finalCode").value.trim()===code){unlock("COMMAND AUTHORITY // RESTORED")}else{time=Math.max(0,time-30);hud();feedback("BYPASS REJECTED // −30 seconds. Recheck inventory recovery order.",true)}}}
function finish(){clearInterval(timer);show("complete");$("#status").textContent="RESTORED";$("#aar").innerHTML=`<div class="terminal">CALLSIGN: ${$("#callsign").value.toUpperCase()}<br>PATH: LET ${level}<br>TIME REMAINING: ${Math.floor(time/60)}:${String(time%60).padStart(2,"0")}<br>HINTS REQUESTED: ${hints}<br>FIREWALLS CLEARED: 5/5<br><br>IG COMMAND NETWORK STATUS: ONLINE</div>`}
hud();inv();
