const rooms=[
{title:"The First Decision",scenario:"Your cadet team has 20 minutes to prepare for an important inspection. Two cadets are arguing, one is confused about the standard, and several others are waiting for direction. What should the leader do FIRST?",q:["Correct the arguing cadets publicly so everyone sees who is in charge.","Quickly assess the situation, clarify the standard, assign responsibilities, and set a check-back time.","Do the most important tasks personally to make sure they are correct.","Wait a few minutes to see whether the team solves the problem on its own."],a:1,h:"Strong leaders create clarity before they create activity."},
{title:"The Integrity Lock",scenario:"You discover that a close friend on your team reported completing a required task that you know was not completed. Nobody else appears to know. Which response best demonstrates leadership and integrity?",q:["Ignore it because correcting a friend could damage team morale.","Complete the task for the cadet without telling anyone.","Address the cadet privately, require the record to be corrected, and follow established procedures.","Tell the entire team what happened so everyone learns from the mistake."],a:2,h:"Integrity means choosing the right action even when loyalty makes it uncomfortable."},
{title:"Priority Override",scenario:"Three things happen at once: a cadet feels faint during outdoor training, your formation is running late, and an instructor is waiting for your accountability report. What is your priority?",q:["Finish the accountability report first.","Keep the formation moving so the schedule is protected.","Address the cadet's immediate safety, delegate accountability, then reorganize the formation.","Ask the cadet to sit down and continue training."],a:2,h:"When priorities compete, consider safety, urgency, and what can be delegated."},
{title:"Communication Breakdown",scenario:"You gave instructions, but half the team performs the task incorrectly. You realize your directions may not have been clear. What is the strongest leadership response?",q:["Hold the team accountable because they should have asked questions.","Accept responsibility for unclear communication, restate the standard, verify understanding, and reset the task.","Select a new team because this group failed.","Say nothing and correct the mistakes yourself."],a:1,h:"Communication is not complete when you speak; it is complete when understanding is confirmed."},
{title:"Final Command Code",scenario:"Your final lock requires the four leadership principles revealed by the challenge. Enter the word formed by the FIRST letter of: Integrity, Responsibility, Accountability, Communication.",code:"IRAC",h:"Look carefully at the first letter of each principle listed in the prompt."}
];
let idx=0,score=1000,time=1800,hints=0,timer,locked=false;const $=s=>document.querySelector(s);
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active')}
$('#begin').onclick=()=>{if(!$('#player').value.trim()){alert('Enter a cadet or team name.');return}show('game');$('#hud').classList.remove('hidden');render();timer=setInterval(()=>{time--;$('#time').textContent=fmt(time);if(time<=0)finish(false)},1000)};
function fmt(s){return Math.floor(s/60)+':'+String(s%60).padStart(2,'0')}
function render(){locked=false;let r=rooms[idx];$('#roomNum').textContent=`${idx+1}/5`;$('#bar').style.width=((idx+1)*20)+'%';$('#roomLabel').textContent=`ROOM 0${idx+1} • ${idx===4?'FINAL LOCK':'LEADERSHIP TEST'}`;$('#roomTitle').textContent=r.title;$('#scenario').textContent=r.scenario;$('#feedback').innerHTML='';$('#feedback').className='';$('#hint').disabled=false;let c=$('#challenge');c.innerHTML='';if(r.q){r.q.forEach((x,i)=>{let b=document.createElement('button');b.className='option';b.textContent=String.fromCharCode(65+i)+'. '+x;b.onclick=()=>answer(i,b);c.appendChild(b)})}else{c.innerHTML='<div class="codeRow"><input id="code" autocomplete="off" placeholder="ENTER 4-LETTER CODE"><button id="unlock">UNLOCK</button></div>';$('#unlock').onclick=codeAnswer}}
function answer(i,b){if(locked)return;let r=rooms[idx];if(i===r.a){locked=true;b.classList.add('correct');feedback('ACCESS GRANTED — Strong leadership decision.','good');setTimeout(next,1300)}else{b.classList.add('wrong');score=Math.max(0,score-75);$('#score').textContent=score;feedback('ACCESS DENIED — Reassess the situation. −75 points','bad');b.disabled=true}}
function codeAnswer(){let v=$('#code').value.trim().toUpperCase();if(v===rooms[idx].code){feedback('FINAL LOCK RELEASED.','good');setTimeout(()=>finish(true),1000)}else{score=Math.max(0,score-75);$('#score').textContent=score;feedback('INCORRECT CODE — −75 points. Try again.','bad')}}
function feedback(t,k){$('#feedback').textContent=t;$('#feedback').className='feedback '+k}
$('#hint').onclick=()=>{if($('#hint').disabled)return;score=Math.max(0,score-50);hints++;$('#score').textContent=score;$('#hint').disabled=true;feedback('HINT: '+rooms[idx].h,'')};
function next(){idx++;if(idx<rooms.length)render();else finish(true)}
function finish(ok){clearInterval(timer);$('#hud').classList.add('hidden');show('finish');$('#resultTitle').textContent=ok?'ESCAPED':'TIME EXPIRED';$('#finalName').textContent=$('#player').value.trim()+' • LET '+$('#level').value;$('#finalScore').textContent=score;$('#finalTime').textContent=fmt(Math.max(0,time));$('#finalHints').textContent=hints;let rank=score>=900?'ELITE LEADER':score>=750?'MISSION READY':score>=550?'DEVELOPING LEADER':'KEEP TRAINING';$('#rank').textContent='LEADERSHIP RATING: '+rank}
