const $=s=>document.querySelector(s);
const P={
3:[
["Hallway 214","You arrive after a bullying incident has already begun. A student is filming; the targeted student says this has happened before.",[
["classify","Evidence Triage",["You personally saw a student filming.","The accused student has bullied the target for months.","The target said, “I've told them to stop.”","The target started today's incident."],["FACT","UNKNOWN","FACT","UNKNOWN"]],
["multi","Immediate Action — choose 3",["Get appropriate adult help","Safely interrupt without physical escalation","Seize the student's phone","Check on the targeted student","Post names online","Promise secrecy"],[0,1,3]],
["decision","New witness says: “He does this every day.”",["Treat it as proven history","Record it as a claim requiring corroboration","Ignore it completely","Ask the witness to post it online"],1],
["defend","Why must a leader separate observation from allegation?",["fact","fair","evidence","trust"]],
["decision","The video goes viral before school staff finish reviewing the incident. What is your responsibility?",["Repeat the most popular version","Only state what you actually know and use proper reporting channels","Defend your friend regardless of evidence","Investigate classmates yourself"],1]]],
["Closing Shift","At a fictional restaurant, an employee reports repeated discriminatory comments. The accused coworker denies it. A customer recorded only the final argument and six orders are waiting.",[
["order","Rank the first four actions",["Reach the manager","Stabilize/separate conflict","Preserve relevant information","Delegate customer flow"],[1,3,0,2]],
["classify","Video Limits",["Video shows final 18 seconds","Video proves weeks of harassment","Customer had a limited recording window","Accused employee is guilty because the clip looks bad"],["FACT","INFERENCE","FACT","INFERENCE"]],
["multi","Choose 3 strongest evidence sources",["Full available video","Employees actually present","Drive-through metric","Prior relevant documented complaints","Online strangers","Rumor from off-duty worker"],[0,1,3]],
["decision","Your friend is the accused employee.",["Remove yourself from every responsibility","Recognize bias risk and ensure fair manager-led process","Automatically believe the complainant","Protect your friend"],1],
["defend","Why is keeping the line moving not enough?",["people","safety","fair","trust","conduct"]]]],
["22-Second Video","You witness only the end of a controversial police encounter. The recording begins after physical contact has already started.",[
["classify","Know vs Assume",["Recording begins after contact","Civilian attacked first","Force is visible in the clip","Earlier officer actions were lawful"],["FACT","UNKNOWN","FACT","UNKNOWN"]],
["order","Responsible Witnessing",["Avoid unsupported claims","Observe safely","Seek appropriate help if danger exists","Report what you actually observed"],[1,2,3,0]],
["decision","A friend posts “WE SAW EVERYTHING.”",["Share it","Correct the overstatement","Add your theory","Say the video proves the entire event"],1],
["multi","Choose 3 useful corroborating sources",["Independent recording of missing period","Witness with clear view","More reposts","Reliable time-stamped records","Online poll"],[0,1,3]],
["defend","Explain why incomplete evidence does not mean do nothing.",["safe","report","observe","evidence","fact"]]]],
["Star Performer","Your best competitor humiliates a quieter cadet. Two cadets say they stopped offering ideas because they expect ridicule. Competition is tomorrow.",[
["multi","Choose 3 long-term risks",["Team trust","Willingness to speak","Retention/development","Social followers","Uniform inventory"],[0,1,2]],
["decision","Captain says wait until after competition.",["Agree because performance comes first","Recognize delay may teach that results excuse misconduct","Remove the cadet permanently without review","Ignore complaints"],1],
["order","Intervention sequence",["Monitor retaliation/climate","Address conduct","Document/report appropriately","Check on affected cadets"],[1,3,2,0]],
["decision","Performance may drop if conduct is addressed.",["Standards should depend on talent","Short-term performance does not erase climate and accountability risks","Cancel competition","Let teammates decide punishment"],1],
["defend","Defend addressing conduct before competition.",["trust","standard","climate","team","long"]]]],
["Crisis Room","At an away event: one cadet is unaccounted for, another reports bullying, a parent posts a false accusation online, buses leave in seven minutes, and you are not the adult in charge.",[
["multi","Choose 3 actions within cadet authority",["Notify responsible adult about missing cadet","Hold disciplinary hearing","Assist accountability","Argue online","Support reporting cadet/preserve info","Promise outcomes"],[0,2,4]],
["order","Rank priorities",["Correct online rumors","Missing cadet accountability","Immediate safety","Accurate information for instructor"],[2,1,3,0]],
["decision","Bus driver pressures the team to leave.",["Leave to protect schedule","Safe accountability controls; elevate to responsible adult","Vote","Leave one cadet behind"],1],
["decision","Parent demands an immediate public answer.",["Debate online","Provide accurate information through responsible adult/authorized channel when facts are established","Ignore the missing cadet to answer parent","Promise an investigation outcome"],1],
["defend","What separates leadership from reacting quickly?",["fact","consequence","respons","priority","evidence"]]]]
],
4:[
["Complaint Before Competition","A cadet reports months of bullying and retaliation by two high performers. One accused cadet is essential tomorrow and is the child of a prominent supporter. Screenshots are cropped.",[
["classify","Evidence Discipline",["Cropped screenshot contains insulting language","Screenshot proves entire relationship","Two independent cadets report similar conduct","Supporter relationship proves favoritism"],["FACT","INFERENCE","FACT","UNKNOWN"]],
["multi","Choose 3 interim controls",["Protect against retaliation","Preserve evidence/gaps","Declare guilt publicly","Appropriate separation/supervision","Guarantee competition role","Ask supporter permission"],[0,1,3]],
["decision","Prominent supporter calls demanding the complaint disappear.",["Comply","Document pressure and preserve fair process through proper authority","Publicly shame supporter","Promise a result"],1],
["decision","Competition performance will likely suffer under interim controls.",["Performance overrides process","Explicitly weigh mission impact but do not trade away safety/fair process","Delay regardless of risk","Automatically cancel competition"],1],
["defend","Defend your recommendation to the instructor.",["trust","standard","retali","fair","process","climate"]]]],
["Restaurant Crisis","You manage a fictional restaurant. A discrimination complaint involves your strongest supervisor. Two witnesses partially corroborate it. You're 25% understaffed. District manager texts: “Keep this quiet and hit the numbers.”",[
["order","Executive Sequence",["Preserve evidence","Stabilize/separate as appropriate","Delegate operations","Follow required management process"],[1,2,0,3]],
["multi","Choose 4 data points",["Full available video","Present witness statements","Sales dashboard","Prior relevant complaints","Employee schedule","Anonymous comments","Popularity score"],[0,1,3,4]],
["decision","How should 'keep this quiet' affect you?",["It overrides process","Treat it as pressure; follow legitimate policy, safety, fair process and documentation","Publish the text","Ignore all management relationships"],1],
["decision","The accused supervisor is the only person who can run drive-through efficiently.",["That makes misconduct irrelevant","Operational value is a real tradeoff but not immunity from standards","Fire immediately without review","Move complainant because it is easier"],1],
["defend","Protect operations AND employees.",["delegate","safety","operation","fair","process","document"]]]],
["Use-of-Force Review","A civic review simulation includes a video starting 31 seconds late, a partially obstructed witness, a later-arriving witness, an officer report, and a viral quote appearing nowhere in supplied evidence.",[
["classify","Source Boundaries",["Video shows events after recording starts","Video proves missing 31 seconds","Witness 1 had partial obstruction","Viral quote is established"],["FACT","UNKNOWN","FACT","UNKNOWN"]],
["order","Reconstruction Method",["Identify contradictions/gaps","Build source timeline","State confidence/unknowns","Compare claims to corroboration"],[1,0,3,2]],
["multi","Choose 3 confidence-builders",["Independent recording of missing period","Clear-view witness","More reposts","Reliable time-stamped records","Class poll"],[0,1,3]],
["decision","Panel chair asks for a conclusion before all evidence is reviewed.",["Give certainty anyway","State provisional findings, limits and next evidence needed","Refuse to discuss anything","Follow social media consensus"],1],
["defend","Brief what is established, disputed, and next.",["establish","unknown","evidence","review","corrobor","fact"]]]],
["Command Climate","Top cadet leader produces exceptional results. Four cadets independently report humiliation and retaliation. Junior attendance fell 18%. Competition results improved.",[
["classify","Signal or Proof",["Four independent complaints form a pattern requiring attention","18% decline proves retaliation caused every absence","Competition results improved","Leader's denial proves complaints false"],["FACT","INFERENCE","FACT","INFERENCE"]],
["multi","Choose 4 system questions",["Are complaints independently consistent?","Evidence of retaliation?","Attendance/retention pattern?","Trophies won?","Standards applied consistently?","Popularity?"],[0,1,2,4]],
["decision","Removing leader may reduce competition performance.",["Never risk performance","Remove solely because complaints exist","Use evidence/authority for interim or accountability action while weighing climate and mission risk","Always wait until after competition"],2],
["decision","No single complaint alone proves the full pattern.",["Therefore ignore all complaints","Analyze corroboration and pattern without pretending aggregation automatically proves every allegation","Publicly identify complainants","Let accused leader investigate"],1],
["defend","What does exemption for a high performer teach the organization?",["trust","standard","report","retali","climate","immun"]]]],
["Strategic Crisis Cell","3:05 PM: cadet unaccounted for off-campus; credible retaliation complaint; parent posts false injury claim; buses must depart in 12 minutes; instructor is handling a separate medical issue. You have three cadet leaders.",[
["multi","Allocate 3 leaders",["Accountability/search support under adult direction","Fight parent online","Preserve retaliation information/protection","Prepare transportation/accountability status","Recruiting flyer"],[0,2,3]],
["order","Strategic Priority",["Reputation response","Safety/accountability","Retaliation process integrity","Transportation coordination"],[1,2,3,0]],
["decision","Late departure costs $600.",["Depart anyway","Safe accountability controls; coordinate delay through adults and document cost","Vote","Leave a cadet leader behind"],1],
["decision","Principal asks why public response is delayed.",["Invent facts to reassure people","Explain that verified safety/accountability information must precede an authoritative response","Blame transportation","Ignore principal"],1],
["defend","Defend accepting cost and delaying public response.",["safety","account","retali","risk","fact","trust","cost","authority"]]]]
]};

let rooms=[],level="3",r=0,t=0,score=3000,time=3600,hints=0,evidence=[],logs=[],timer;function show(a){["start","game","finish"].forEach(x=>$("#"+x).classList.add("hide"));$("#"+a).classList.remove("hide")}
$("#begin").onclick=()=>{if(!$("#name").value.trim())return alert("Enter a name.");level=$("#level").value;rooms=P[level];show("game");$("#hud").classList.remove("hide");render();timer=setInterval(()=>{time--;$("#time").textContent=Math.floor(time/60)+":"+String(time%60).padStart(2,"0");if(time<=0)finish()},1000)}
function render(){let room=rooms[r],task=room[2][t];$("#caseNo").textContent=`${r+1}/5`;$("#label").textContent=`LET ${level} • CASE ${r+1} • DECISION ${t+1}/5`;$("#title").textContent=room[0];$("#brief").textContent=room[1];$("#feedback").innerHTML="";$("#hint").disabled=false;$("#cases").innerHTML=rooms.map((x,i)=>`<div class="casebox ${i<r?"done":i===r?"current":""}">${i<r?"✓":"CASE "+(i+1)}</div>`).join("");draw(task)}
function draw(x){let type=x[0],box=$("#task");box.innerHTML=`<h3 class="tag">${x[1]}</h3>`;if(type==="decision"){x[2].forEach((o,i)=>{let b=document.createElement("button");b.className="choice";b.textContent=o;b.onclick=()=>decision(i,x);box.appendChild(b)})}else if(type==="multi"){box.innerHTML+=`<p>Select exactly ${x[4].length} actions, then commit.</p><div id="opts"></div><button id="commit">COMMIT</button>`;let s=[];x[2].forEach((o,i)=>{let b=document.createElement("button");b.className="choice";b.textContent=o;b.onclick=()=>{if(s.includes(i)){s=s.filter(v=>v!==i);b.classList.remove("sel")}else if(s.length<x[4].length){s.push(i);b.classList.add("sel")}};$("#opts").appendChild(b)});$("#commit").onclick=()=>{if(s.length!==x[4].length)return;let hit=s.filter(i=>x[4].includes(i)).length;commit((x[4].length-hit)*100,`${hit}/${x[4].length} priority actions aligned`)}}else if(type==="classify"){let cats=["FACT","CLAIM","INFERENCE","UNKNOWN"],a=Array(x[2].length).fill("");x[2].forEach((it,i)=>{box.innerHTML+=`<div class="evidence"><b>${it}</b><div id="c${i}"></div></div>`;cats.forEach(c=>{let b=document.createElement("button");b.type="button";b.className="classifyBtn";b.textContent=c;b.addEventListener("click",(ev)=>{ev.preventDefault();a[i]=c;const group=document.getElementById("c"+i);group.querySelectorAll("button").forEach(q=>q.classList.remove("sel"));b.classList.add("sel")});document.getElementById("c"+i).appendChild(b)})});let b=document.createElement("button");b.textContent="COMMIT CLASSIFICATION";b.onclick=()=>{if(a.some(v=>!v))return;let hit=a.filter((v,i)=>v===x[3][i]).length;commit((x[3].length-hit)*80,`${hit}/${x[3].length} evidence classifications correct`)};box.appendChild(b)}else if(type==="order"){box.innerHTML+=`<p>Click every item in priority order.</p><div id="ord"></div><button id="commit">COMMIT ORDER</button>`;let a=[];x[2].forEach((it,i)=>{let b=document.createElement("button");b.className="choice";b.textContent=it;b.onclick=()=>{if(!a.includes(i)){a.push(i);b.classList.add("sel");b.textContent=`${a.length}. ${it}`}};$("#ord").appendChild(b)});$("#commit").onclick=()=>{if(a.length!==x[2].length)return;let hit=a.filter((v,i)=>v===x[3][i]).length;commit((x[3].length-hit)*70,`${hit}/${x[3].length} priorities in strongest position`)}}else if(type==="defend"){box.innerHTML+=`<p>${x[1]}</p><textarea id="def" placeholder="Defend your decision in 2–4 sentences. Address tradeoffs and consequences."></textarea><button id="commit">SUBMIT DEFENSE</button>`;$("#commit").onclick=()=>{let v=$("#def").value.trim().toLowerCase();if(v.length<55)return alert("Your defense needs more reasoning.");let hit=x[2].filter(k=>v.includes(k)).length;commit(hit>=2?0:hit===1?100:200,hit>=2?"Reasoned defense":"Defense needs stronger leadership analysis")}}}
function decision(i,x){let best=x[3],loss=i===best?0:150;commit(loss,i===best?"Strong judgment":"Decision accepted with consequence")}
function commit(loss,msg){score-=loss;$("#score").textContent=score;logs.push(`Case ${r+1}: ${msg}${loss?" (−"+loss+")":""}`);$("#feedback").innerHTML=`<div class="${loss?"warn":"good"}"><b>${msg}</b>${loss?` • −${loss}`:""}<div class="consequence">The decision is locked. Leadership means living with consequences, not clicking until the game says “correct.”</div></div>`;setTimeout(next,1300)}
function next(){t++;if(t>=5){evidence.push(`Case ${r+1} completed: ${rooms[r][0]}`);r++;t=0}if(r>=5)finish();else render()}
$("#hint").onclick=()=>{score-=125;hints++;$("#score").textContent=score;$("#hint").disabled=true;$("#feedback").innerHTML=`<div class="warn">ANALYST HINT: Identify what is known, what is assumed, who is at risk, what authority you actually have, and the second-order consequence. −125</div>`}
$("#file").onclick=()=>{let d=$("#drawer");d.classList.toggle("hide");d.innerHTML="<h3>CASE FILE</h3>"+(evidence.length?evidence.map(e=>`<div class='evidence'>${e}</div>`).join(""):"No completed case evidence yet.")}
$("#log").onclick=()=>{let d=$("#drawer");d.classList.toggle("hide");d.innerHTML="<h3>DECISION LOG</h3>"+(logs.length?logs.map(e=>`<div class='evidence'>${e}</div>`).join(""):"No decisions yet.")}
function finish(){clearInterval(timer);$("#hud").classList.add("hide");show("finish");$("#who").textContent=$("#name").value+` • LET ${level}`;$("#results").innerHTML=`<h2>${Math.max(0,score)} JUDGMENT POINTS</h2><p>${hints} hints used • ${Math.floor(Math.max(0,time)/60)}:${String(Math.max(0,time)%60).padStart(2,"0")} remaining</p><div class="evidence">${logs.slice(-8).join("<br>")}</div>`}
